build_mau:
  outputs:
    dev:
      account: adblxdq-gc33558
      database: dev
      password: gemsoL%1234
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: deekshachauhan7
      warehouse: COMPUTE_WH
  target: dev
